pipeline:
  name: twitter-pipeline
  identifier: twitterpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: twitterclone
        repoName: twitter-clone
        build: <+input>
  stages:
    - stage:
        name: build-stage
        identifier: buildstage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: testdevseccopsekscluster
              namespace: test-ns
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: aws
                    region: ap-south-1
                    account: "130705418859"
                    imageName: twitter-clone
                    tags:
                      - h-twitter-tag
                    dockerfile: Dockerfile
                    context: .
